// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.bs.js";
import * as React from "react";
import * as App$WebappTemplate from "../src/App.bs.js";
import * as ReactTestingLibrary from "rescript-react-testing-library/src/ReactTestingLibrary.bs.js";

function toMatchSnapshot(a) {
  return Jest.Expect.toMatchSnapshot(a);
}

Jest.describe("App", (function (param) {
        beforeEach(function () {
              return ReactTestingLibrary.renderOnScreen(React.createElement(App$WebappTemplate.make, {}));
            });
        return Jest.test("test title", (function (param) {
                      return Jest.Expect.toMatchSnapshot(Jest.Expect.expect(ReactTestingLibrary.getByRole(undefined, {
                                          NAME: "Str",
                                          VAL: "heading"
                                        }, document)));
                    }));
      }));

export {
  toMatchSnapshot ,
  
}
/*  Not a pure module */
