name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/anyakichi/webapp-template:main
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn lint
